version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  sonarcloud: sonarsource/sonarcloud@1.1.0
jobs:
  run_tests:
    executor: node/default
    docker:
      - image: circleci/node:17.2.0
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install --save
      - run:
          name: Run Tests (Coverage, Unit test, Integration test)
          command: npm test
      - sonarcloud/scan
workflows:
  heroku_deploy:
    jobs:
      - run_tests
      - heroku/deploy-via-git:
          requires:
            - run_tests


